from collections.abc import Mapping
from typing import Any


def _model(
    slug: str,
    name: str,
    provider: str,
    *,
    family: str,
    release_date: str,
    modality: str,
    context_window_tokens: int | None,
    max_output_tokens: int | None,
    parameters: str | None,
    license_name: str,
    open_weights: bool,
    availability: str,
    input_price_per_million_usd: float | None,
    output_price_per_million_usd: float | None,
    reasoning: bool,
    multimodal: bool,
    fine_tune_available: bool,
    knowledge_cutoff: str | None,
    architecture: str,
    deployment_options: list[str],
    typical_use_cases: list[str],
    strengths: list[str],
    limitations: list[str],
    safety_notes: str,
    documentation_url: str,
    benchmarks: dict[str, str | float | None],
    extra: dict[str, Any] | None = None,
) -> dict[str, Any]:
    record: dict[str, Any] = {
        "slug": slug,
        "name": name,
        "provider": provider,
        "family": family,
        "release_date": release_date,
        "modality": modality,
        "context_window_tokens": context_window_tokens,
        "max_output_tokens": max_output_tokens,
        "parameters": parameters,
        "license_name": license_name,
        "open_weights": open_weights,
        "availability": availability,
        "input_price_per_million_usd": input_price_per_million_usd,
        "output_price_per_million_usd": output_price_per_million_usd,
        "reasoning": reasoning,
        "multimodal": multimodal,
        "fine_tune_available": fine_tune_available,
        "knowledge_cutoff": knowledge_cutoff,
        "architecture": architecture,
        "deployment_options": deployment_options,
        "typical_use_cases": typical_use_cases,
        "strengths": strengths,
        "limitations": limitations,
        "safety_notes": safety_notes,
        "documentation_url": documentation_url,
        "benchmarks": benchmarks,
        "pricing_notes": (
            "List prices are indicative public API rates in USD per million tokens where "
            "published, and can change without notice."
        ),
    }
    if extra:
        record.update(extra)
    return record


_API = ["hosted API"]
_API_WEIGHTS = ["hosted API", "self-hosted weights"]
_WEIGHTS = ["self-hosted weights"]
_CLOSED = ["hosted API", "managed cloud"]


def model_catalog() -> list[Mapping[str, Any]]:
    return [
        _model(
            "gpt-4o",
            "GPT-4o",
            "OpenAI",
            family="GPT-4o",
            release_date="2024-05-13",
            modality="multimodal",
            context_window_tokens=128000,
            max_output_tokens=16384,
            parameters=None,
            license_name="Proprietary",
            open_weights=False,
            availability="API",
            input_price_per_million_usd=2.5,
            output_price_per_million_usd=10.0,
            reasoning=False,
            multimodal=True,
            fine_tune_available=True,
            knowledge_cutoff="2023-10",
            architecture="Dense transformer, omni text-audio-vision training",
            deployment_options=_CLOSED,
            typical_use_cases=["assistants", "document Q&A", "vision", "voice agents"],
            strengths=["strong general quality", "native vision", "broad tool ecosystem"],
            limitations=["closed weights", "rate and policy limits", "cost at high volume"],
            safety_notes="Filtered hosted API with usage policies and monitoring.",
            documentation_url="https://platform.openai.com/docs/models/gpt-4o",
            benchmarks={"mmlu": 88.7, "gpqa": 53.6, "humaneval": 90.2, "mmmu": 69.1},
        ),
        _model(
            "gpt-4o-mini",
            "GPT-4o mini",
            "OpenAI",
            family="GPT-4o",
            release_date="2024-07-18",
            modality="multimodal",
            context_window_tokens=128000,
            max_output_tokens=16384,
            parameters=None,
            license_name="Proprietary",
            open_weights=False,
            availability="API",
            input_price_per_million_usd=0.15,
            output_price_per_million_usd=0.6,
            reasoning=False,
            multimodal=True,
            fine_tune_available=True,
            knowledge_cutoff="2023-10",
            architecture="Distilled omni model optimized for cost",
            deployment_options=_CLOSED,
            typical_use_cases=["classification", "extraction", "high-volume chat"],
            strengths=["low latency", "low cost", "solid instruction following"],
            limitations=["weaker than flagship on hard reasoning"],
            safety_notes="Same hosted safety stack as other OpenAI chat models.",
            documentation_url="https://platform.openai.com/docs/models/gpt-4o-mini",
            benchmarks={"mmlu": 82.0, "gpqa": 40.2, "humaneval": 87.2, "mmmu": 59.4},
        ),
        _model(
            "gpt-4-1",
            "GPT-4.1",
            "OpenAI",
            family="GPT-4.1",
            release_date="2025-04-14",
            modality="multimodal",
            context_window_tokens=1047576,
            max_output_tokens=32768,
            parameters=None,
            license_name="Proprietary",
            open_weights=False,
            availability="API",
            input_price_per_million_usd=2.0,
            output_price_per_million_usd=8.0,
            reasoning=False,
            multimodal=True,
            fine_tune_available=True,
            knowledge_cutoff="2024-06",
            architecture="Long-context GPT successor focused on coding and instruction",
            deployment_options=_CLOSED,
            typical_use_cases=["long-document analysis", "software engineering", "agents"],
            strengths=["1M-class context", "improved coding", "better instruction following"],
            limitations=["price grows with context", "closed evaluation details"],
            safety_notes="Hosted model with OpenAI usage policies.",
            documentation_url="https://platform.openai.com/docs/models/gpt-4.1",
            benchmarks={"mmlu": 90.2, "swe_bench": 54.6, "gpqa": 66.3},
        ),
        _model(
            "o3",
            "OpenAI o3",
            "OpenAI",
            family="o-series",
            release_date="2025-04-16",
            modality="text",
            context_window_tokens=200000,
            max_output_tokens=100000,
            parameters=None,
            license_name="Proprietary",
            open_weights=False,
            availability="API",
            input_price_per_million_usd=10.0,
            output_price_per_million_usd=40.0,
            reasoning=True,
            multimodal=True,
            fine_tune_available=False,
            knowledge_cutoff="2024-06",
            architecture="Deliberative reasoning model with hidden chain-of-thought",
            deployment_options=_CLOSED,
            typical_use_cases=["hard STEM", "research assistance", "complex planning"],
            strengths=["state-of-the-art reasoning", "strong science and coding"],
            limitations=["higher latency", "higher cost", "overthinking simple tasks"],
            safety_notes="Deliberative alignment; still requires application-level controls.",
            documentation_url="https://platform.openai.com/docs/models/o3",
            benchmarks={"gpqa": 83.3, "aime": 88.9, "swe_bench": 69.1},
        ),
        _model(
            "o4-mini",
            "OpenAI o4-mini",
            "OpenAI",
            family="o-series",
            release_date="2025-04-16",
            modality="multimodal",
            context_window_tokens=200000,
            max_output_tokens=100000,
            parameters=None,
            license_name="Proprietary",
            open_weights=False,
            availability="API",
            input_price_per_million_usd=1.1,
            output_price_per_million_usd=4.4,
            reasoning=True,
            multimodal=True,
            fine_tune_available=False,
            knowledge_cutoff="2024-06",
            architecture="Smaller reasoning model in the o-series",
            deployment_options=_CLOSED,
            typical_use_cases=["affordable reasoning", "STEM tutoring", "code review"],
            strengths=["strong reasoning for price", "vision-enabled reasoning"],
            limitations=["can still be slow vs non-reasoning models"],
            safety_notes="Hosted reasoning safety stack.",
            documentation_url="https://platform.openai.com/docs/models/o4-mini",
            benchmarks={"gpqa": 81.4, "aime": 93.4, "swe_bench": 68.1},
        ),
        _model(
            "gpt-5",
            "GPT-5",
            "OpenAI",
            family="GPT-5",
            release_date="2025-08-07",
            modality="multimodal",
            context_window_tokens=256000,
            max_output_tokens=128000,
            parameters=None,
            license_name="Proprietary",
            open_weights=False,
            availability="API",
            input_price_per_million_usd=1.25,
            output_price_per_million_usd=10.0,
            reasoning=True,
            multimodal=True,
            fine_tune_available=False,
            knowledge_cutoff="2024-10",
            architecture="Unified flagship with adaptive reasoning effort",
            deployment_options=_CLOSED,
            typical_use_cases=["general assistant", "agents", "professional knowledge work"],
            strengths=["broad capability", "adaptive reasoning", "strong coding"],
            limitations=["closed system card details vary by SKU"],
            safety_notes="Updated model spec and usage policies; verify the SKU in use.",
            documentation_url="https://platform.openai.com/docs/models/gpt-5",
            benchmarks={"gpqa": 88.4, "swe_bench": 74.9, "mmlu": 91.4},
        ),
        _model(
            "claude-opus-4-1",
            "Claude Opus 4.1",
            "Anthropic",
            family="Claude 4",
            release_date="2025-08-05",
            modality="multimodal",
            context_window_tokens=200000,
            max_output_tokens=32000,
            parameters=None,
            license_name="Proprietary",
            open_weights=False,
            availability="API",
            input_price_per_million_usd=15.0,
            output_price_per_million_usd=75.0,
            reasoning=True,
            multimodal=True,
            fine_tune_available=False,
            knowledge_cutoff="2025-03",
            architecture="Constitutional AI flagship with extended thinking",
            deployment_options=_CLOSED,
            typical_use_cases=["complex coding", "research", "long-running agents"],
            strengths=["coding agents", "careful instruction following", "long context"],
            limitations=["premium price", "closed weights"],
            safety_notes="Constitutional AI, ASL-style deployment policy, usage limits.",
            documentation_url="https://docs.anthropic.com/en/docs/about-claude/models",
            benchmarks={"swe_bench": 74.5, "gpqa": 80.9, "tau_bench": 81.4},
        ),
        _model(
            "claude-sonnet-4",
            "Claude Sonnet 4",
            "Anthropic",
            family="Claude 4",
            release_date="2025-05-22",
            modality="multimodal",
            context_window_tokens=200000,
            max_output_tokens=64000,
            parameters=None,
            license_name="Proprietary",
            open_weights=False,
            availability="API",
            input_price_per_million_usd=3.0,
            output_price_per_million_usd=15.0,
            reasoning=True,
            multimodal=True,
            fine_tune_available=False,
            knowledge_cutoff="2025-03",
            architecture="Balanced Claude 4 hybrid reasoning model",
            deployment_options=_CLOSED,
            typical_use_cases=["product assistants", "coding", "enterprise search"],
            strengths=["quality/cost balance", "strong writing", "tool use"],
            limitations=["not the absolute top of the Claude stack on hardest tasks"],
            safety_notes="Anthropic usage policy and classifiers apply.",
            documentation_url="https://docs.anthropic.com/en/docs/about-claude/models",
            benchmarks={"swe_bench": 72.7, "gpqa": 75.4, "mmlu": 88.0},
        ),
        _model(
            "claude-haiku-3-5",
            "Claude 3.5 Haiku",
            "Anthropic",
            family="Claude 3.5",
            release_date="2024-11-04",
            modality="multimodal",
            context_window_tokens=200000,
            max_output_tokens=8192,
            parameters=None,
            license_name="Proprietary",
            open_weights=False,
            availability="API",
            input_price_per_million_usd=0.8,
            output_price_per_million_usd=4.0,
            reasoning=False,
            multimodal=True,
            fine_tune_available=False,
            knowledge_cutoff="2024-07",
            architecture="Fast Claude 3.5-class model",
            deployment_options=_CLOSED,
            typical_use_cases=["moderation", "extraction", "low-latency chat"],
            strengths=["speed", "cost", "reliable formatting"],
            limitations=["weaker deep reasoning than Sonnet/Opus"],
            safety_notes="Same Anthropic policy stack as other Claude models.",
            documentation_url="https://docs.anthropic.com/en/docs/about-claude/models",
            benchmarks={"mmlu": 73.0, "humaneval": 88.1},
        ),
        _model(
            "gemini-2-5-pro",
            "Gemini 2.5 Pro",
            "Google",
            family="Gemini 2.5",
            release_date="2025-03-25",
            modality="multimodal",
            context_window_tokens=1048576,
            max_output_tokens=65536,
            parameters=None,
            license_name="Proprietary",
            open_weights=False,
            availability="API",
            input_price_per_million_usd=1.25,
            output_price_per_million_usd=10.0,
            reasoning=True,
            multimodal=True,
            fine_tune_available=True,
            knowledge_cutoff="2025-01",
            architecture="Sparse Mixture-of-Experts natively multimodal model",
            deployment_options=["Google AI Studio", "Vertex AI"],
            typical_use_cases=["long-context analysis", "code", "video/audio understanding"],
            strengths=["native multimodality", "1M context", "strong reasoning"],
            limitations=["provider lock-in", "quota variability by region"],
            safety_notes="Google content filters and Vertex safety settings.",
            documentation_url="https://ai.google.dev/gemini-api/docs/models",
            benchmarks={"gpqa": 86.4, "aime": 86.7, "swe_bench": 63.8},
        ),
        _model(
            "gemini-2-5-flash",
            "Gemini 2.5 Flash",
            "Google",
            family="Gemini 2.5",
            release_date="2025-04-17",
            modality="multimodal",
            context_window_tokens=1048576,
            max_output_tokens=65536,
            parameters=None,
            license_name="Proprietary",
            open_weights=False,
            availability="API",
            input_price_per_million_usd=0.3,
            output_price_per_million_usd=2.5,
            reasoning=True,
            multimodal=True,
            fine_tune_available=True,
            knowledge_cutoff="2025-01",
            architecture="Fast Gemini 2.5 with thinking budgets",
            deployment_options=["Google AI Studio", "Vertex AI"],
            typical_use_cases=["high-volume assistants", "extraction", "cheap long context"],
            strengths=["price", "speed", "long context"],
            limitations=["below Pro on hardest STEM"],
            safety_notes="Configurable safety filters on Vertex.",
            documentation_url="https://ai.google.dev/gemini-api/docs/models",
            benchmarks={"gpqa": 82.4, "swe_bench": 60.3},
        ),
        _model(
            "gemini-2-0-flash",
            "Gemini 2.0 Flash",
            "Google",
            family="Gemini 2.0",
            release_date="2024-12-11",
            modality="multimodal",
            context_window_tokens=1048576,
            max_output_tokens=8192,
            parameters=None,
            license_name="Proprietary",
            open_weights=False,
            availability="API",
            input_price_per_million_usd=0.1,
            output_price_per_million_usd=0.4,
            reasoning=False,
            multimodal=True,
            fine_tune_available=True,
            knowledge_cutoff="2024-08",
            architecture="Workhorse multimodal Gemini 2.0",
            deployment_options=["Google AI Studio", "Vertex AI"],
            typical_use_cases=["realtime agents", "vision", "tool calling"],
            strengths=["very low cost", "native tools and vision"],
            limitations=["weaker than 2.5 on reasoning"],
            safety_notes="Google safety settings apply.",
            documentation_url="https://ai.google.dev/gemini-api/docs/models",
            benchmarks={"mmlu": 76.4, "mmmu": 71.7},
        ),
        _model(
            "gemma-3-27b",
            "Gemma 3 27B",
            "Google",
            family="Gemma 3",
            release_date="2025-03-12",
            modality="multimodal",
            context_window_tokens=131072,
            max_output_tokens=8192,
            parameters="27B",
            license_name="Gemma Terms of Use",
            open_weights=True,
            availability="weights and API",
            input_price_per_million_usd=None,
            output_price_per_million_usd=None,
            reasoning=False,
            multimodal=True,
            fine_tune_available=True,
            knowledge_cutoff=None,
            architecture="Open Gemma 3 dense multimodal model",
            deployment_options=_API_WEIGHTS,
            typical_use_cases=["private RAG", "on-prem chat", "fine-tuning"],
            strengths=["open weights", "strong 27B quality", "multimodal"],
            limitations=["license restrictions", "self-hosting cost"],
            safety_notes="Open model; safety is the deployer’s responsibility.",
            documentation_url="https://ai.google.dev/gemma",
            benchmarks={"mmlu": 78.6, "humaneval": 76.2},
        ),
        _model(
            "llama-4-scout",
            "Llama 4 Scout",
            "Meta",
            family="Llama 4",
            release_date="2025-04-05",
            modality="multimodal",
            context_window_tokens=10000000,
            max_output_tokens=8192,
            parameters="109B MoE (17B active)",
            license_name="Llama 4 Community License",
            open_weights=True,
            availability="weights and API",
            input_price_per_million_usd=None,
            output_price_per_million_usd=None,
            reasoning=False,
            multimodal=True,
            fine_tune_available=True,
            knowledge_cutoff="2024-08",
            architecture="Mixture-of-Experts natively multimodal Llama 4",
            deployment_options=_API_WEIGHTS,
            typical_use_cases=["long-context RAG", "open multimodal apps"],
            strengths=["open weights", "very long context", "MoE efficiency"],
            limitations=["serving complexity", "license acceptable-use limits"],
            safety_notes="Llama acceptable use policy; no hosted filter unless you add one.",
            documentation_url="https://www.llama.com/models/llama-4/",
            benchmarks={"mmlu": 81.0, "mmmu": 73.4},
        ),
        _model(
            "llama-4-maverick",
            "Llama 4 Maverick",
            "Meta",
            family="Llama 4",
            release_date="2025-04-05",
            modality="multimodal",
            context_window_tokens=1000000,
            max_output_tokens=8192,
            parameters="400B MoE (17B active)",
            license_name="Llama 4 Community License",
            open_weights=True,
            availability="weights and API",
            input_price_per_million_usd=None,
            output_price_per_million_usd=None,
            reasoning=False,
            multimodal=True,
            fine_tune_available=True,
            knowledge_cutoff="2024-08",
            architecture="Larger Llama 4 MoE expert",
            deployment_options=_API_WEIGHTS,
            typical_use_cases=["open flagship assistant", "multimodal agents"],
            strengths=["open high quality", "MoE cost profile"],
            limitations=["heavy infrastructure", "community license terms"],
            safety_notes="Deployer-operated safety.",
            documentation_url="https://www.llama.com/models/llama-4/",
            benchmarks={"mmlu": 85.5, "gpqa": 69.8},
        ),
        _model(
            "llama-3-3-70b",
            "Llama 3.3 70B Instruct",
            "Meta",
            family="Llama 3",
            release_date="2024-12-06",
            modality="text",
            context_window_tokens=131072,
            max_output_tokens=8192,
            parameters="70B",
            license_name="Llama 3.3 Community License",
            open_weights=True,
            availability="weights and API",
            input_price_per_million_usd=0.4,
            output_price_per_million_usd=0.4,
            reasoning=False,
            multimodal=False,
            fine_tune_available=True,
            knowledge_cutoff="2023-12",
            architecture="Dense Llama 3.3 instruct model",
            deployment_options=_API_WEIGHTS,
            typical_use_cases=["self-hosted chat", "RAG", "fine-tunes"],
            strengths=["mature ecosystem", "strong 70B quality"],
            limitations=["text-only", "older than Llama 4"],
            safety_notes="Llama AUP; many hosts add extra filters.",
            documentation_url="https://www.llama.com/models/llama-3/",
            benchmarks={"mmlu": 86.0, "humaneval": 88.4},
        ),
        _model(
            "llama-3-1-405b",
            "Llama 3.1 405B Instruct",
            "Meta",
            family="Llama 3.1",
            release_date="2024-07-23",
            modality="text",
            context_window_tokens=131072,
            max_output_tokens=4096,
            parameters="405B",
            license_name="Llama 3.1 Community License",
            open_weights=True,
            availability="weights and API",
            input_price_per_million_usd=3.5,
            output_price_per_million_usd=3.5,
            reasoning=False,
            multimodal=False,
            fine_tune_available=True,
            knowledge_cutoff="2023-12",
            architecture="Dense 405B Llama 3.1",
            deployment_options=_API_WEIGHTS,
            typical_use_cases=["open flagship text", "synthetic data", "distillation teacher"],
            strengths=["open 405B quality", "long context"],
            limitations=["expensive to host", "superseded by Llama 4 for many uses"],
            safety_notes="Open weights; safety depends on serving stack.",
            documentation_url="https://www.llama.com/models/llama-3/",
            benchmarks={"mmlu": 88.6, "gpqa": 51.1},
        ),
        _model(
            "mistral-large-2",
            "Mistral Large 2",
            "Mistral AI",
            family="Mistral Large",
            release_date="2024-07-24",
            modality="text",
            context_window_tokens=131072,
            max_output_tokens=8192,
            parameters="123B",
            license_name="Mistral Research License / API commercial",
            open_weights=True,
            availability="weights and API",
            input_price_per_million_usd=2.0,
            output_price_per_million_usd=6.0,
            reasoning=False,
            multimodal=False,
            fine_tune_available=True,
            knowledge_cutoff="2024-04",
            architecture="Dense multilingual Mistral flagship",
            deployment_options=_API_WEIGHTS,
            typical_use_cases=["EU-hosted assistants", "function calling", "multilingual"],
            strengths=["strong multilingual", "function calling", "self-host option"],
            limitations=["weights license is not fully permissive"],
            safety_notes="API moderation optional; self-host is operator-owned.",
            documentation_url="https://docs.mistral.ai/getting-started/models/",
            benchmarks={"mmlu": 84.0, "humaneval": 92.1},
        ),
        _model(
            "mistral-small-3-1",
            "Mistral Small 3.1",
            "Mistral AI",
            family="Mistral Small",
            release_date="2025-03-17",
            modality="multimodal",
            context_window_tokens=131072,
            max_output_tokens=8192,
            parameters="24B",
            license_name="Apache 2.0",
            open_weights=True,
            availability="weights and API",
            input_price_per_million_usd=0.1,
            output_price_per_million_usd=0.3,
            reasoning=False,
            multimodal=True,
            fine_tune_available=True,
            knowledge_cutoff=None,
            architecture="Apache-licensed 24B multimodal model",
            deployment_options=_API_WEIGHTS,
            typical_use_cases=["local apps", "vision+text", "fine-tuning"],
            strengths=["permissive license", "efficient 24B", "vision"],
            limitations=["below flagship on hardest tasks"],
            safety_notes="Open model; add your own policy layer.",
            documentation_url="https://docs.mistral.ai/getting-started/models/",
            benchmarks={"mmlu": 81.0, "mmmu": 64.0},
        ),
        _model(
            "mixtral-8x22b",
            "Mixtral 8x22B",
            "Mistral AI",
            family="Mixtral",
            release_date="2024-04-17",
            modality="text",
            context_window_tokens=65536,
            max_output_tokens=4096,
            parameters="141B MoE (39B active)",
            license_name="Apache 2.0",
            open_weights=True,
            availability="weights and API",
            input_price_per_million_usd=1.2,
            output_price_per_million_usd=1.2,
            reasoning=False,
            multimodal=False,
            fine_tune_available=True,
            knowledge_cutoff=None,
            architecture="Sparse Mixture-of-Experts decoder",
            deployment_options=_API_WEIGHTS,
            typical_use_cases=["open MoE serving", "code", "multilingual"],
            strengths=["Apache license", "MoE efficiency"],
            limitations=["older than Mistral Small/Large 2 class"],
            safety_notes="Open weights.",
            documentation_url="https://mistral.ai/news/mixtral-8x22b",
            benchmarks={"mmlu": 77.8, "humaneval": 45.1},
        ),
        _model(
            "codestral",
            "Codestral",
            "Mistral AI",
            family="Codestral",
            release_date="2024-05-29",
            modality="code",
            context_window_tokens=32768,
            max_output_tokens=8192,
            parameters="22B",
            license_name="Mistral Non-Production / API",
            open_weights=True,
            availability="weights and API",
            input_price_per_million_usd=0.3,
            output_price_per_million_usd=0.9,
            reasoning=False,
            multimodal=False,
            fine_tune_available=True,
            knowledge_cutoff=None,
            architecture="Code-specialized decoder",
            deployment_options=_API_WEIGHTS,
            typical_use_cases=["fill-in-the-middle", "IDE completion", "code chat"],
            strengths=["code FIM", "low latency"],
            limitations=["not a general chatbot"],
            safety_notes="Code models can emit insecure snippets; review required.",
            documentation_url="https://docs.mistral.ai/capabilities/code_generation/",
            benchmarks={"humaneval": 81.1, "mbpp": 78.2},
        ),
        _model(
            "pixtral-large",
            "Pixtral Large",
            "Mistral AI",
            family="Pixtral",
            release_date="2024-11-18",
            modality="multimodal",
            context_window_tokens=128000,
            max_output_tokens=8192,
            parameters="124B",
            license_name="Mistral Research License / API",
            open_weights=True,
            availability="weights and API",
            input_price_per_million_usd=2.0,
            output_price_per_million_usd=6.0,
            reasoning=False,
            multimodal=True,
            fine_tune_available=True,
            knowledge_cutoff=None,
            architecture="Multimodal decoder with vision encoder",
            deployment_options=_API_WEIGHTS,
            typical_use_cases=["document understanding", "chart QA", "vision agents"],
            strengths=["open multimodal flagship from Mistral"],
            limitations=["research license on weights"],
            safety_notes="Vision models can leak private document content; control inputs.",
            documentation_url="https://mistral.ai/news/pixtral-large",
            benchmarks={"mmmu": 64.0, "mathvista": 69.4},
        ),
        _model(
            "deepseek-v3",
            "DeepSeek-V3",
            "DeepSeek",
            family="DeepSeek-V3",
            release_date="2024-12-26",
            modality="text",
            context_window_tokens=128000,
            max_output_tokens=8192,
            parameters="671B MoE (37B active)",
            license_name="MIT",
            open_weights=True,
            availability="weights and API",
            input_price_per_million_usd=0.27,
            output_price_per_million_usd=1.1,
            reasoning=False,
            multimodal=False,
            fine_tune_available=True,
            knowledge_cutoff=None,
            architecture="Multi-head latent attention MoE",
            deployment_options=_API_WEIGHTS,
            typical_use_cases=["low-cost flagship chat", "coding", "self-host"],
            strengths=["MIT license", "very strong quality/price"],
            limitations=["export/compliance review for some orgs", "serving complexity"],
            safety_notes="Open model; no vendor safety SLA unless using their API.",
            documentation_url="https://github.com/deepseek-ai/DeepSeek-V3",
            benchmarks={"mmlu": 87.1, "humaneval": 82.6, "gpqa": 59.1},
        ),
        _model(
            "deepseek-r1",
            "DeepSeek-R1",
            "DeepSeek",
            family="DeepSeek-R1",
            release_date="2025-01-20",
            modality="text",
            context_window_tokens=128000,
            max_output_tokens=32768,
            parameters="671B MoE",
            license_name="MIT",
            open_weights=True,
            availability="weights and API",
            input_price_per_million_usd=0.55,
            output_price_per_million_usd=2.19,
            reasoning=True,
            multimodal=False,
            fine_tune_available=True,
            knowledge_cutoff=None,
            architecture="Reasoning model distilled/trained with RL",
            deployment_options=_API_WEIGHTS,
            typical_use_cases=["open reasoning", "math", "competitive coding"],
            strengths=["open reasoning quality", "distilled smaller variants"],
            limitations=["verbose traces", "variable safety"],
            safety_notes="Reasoning traces may include sensitive intermediate content.",
            documentation_url="https://github.com/deepseek-ai/DeepSeek-R1",
            benchmarks={"aime": 79.8, "gpqa": 71.5, "swe_bench": 49.2},
        ),
        _model(
            "qwen2-5-72b",
            "Qwen2.5-72B Instruct",
            "Alibaba",
            family="Qwen2.5",
            release_date="2024-09-19",
            modality="text",
            context_window_tokens=131072,
            max_output_tokens=8192,
            parameters="72B",
            license_name="Qwen License",
            open_weights=True,
            availability="weights and API",
            input_price_per_million_usd=0.4,
            output_price_per_million_usd=1.2,
            reasoning=False,
            multimodal=False,
            fine_tune_available=True,
            knowledge_cutoff=None,
            architecture="Dense Qwen2.5 instruct",
            deployment_options=_API_WEIGHTS,
            typical_use_cases=["multilingual", "coding", "self-host"],
            strengths=["strong Chinese/English", "coding", "long context"],
            limitations=["custom license", "region policy considerations"],
            safety_notes="Open weights; API may apply extra filters.",
            documentation_url="https://qwenlm.github.io/",
            benchmarks={"mmlu": 86.1, "humaneval": 86.6},
        ),
        _model(
            "qwen2-5-max",
            "Qwen2.5-Max",
            "Alibaba",
            family="Qwen2.5",
            release_date="2025-01-28",
            modality="text",
            context_window_tokens=131072,
            max_output_tokens=8192,
            parameters="MoE (undisclosed)",
            license_name="Proprietary API",
            open_weights=False,
            availability="API",
            input_price_per_million_usd=1.6,
            output_price_per_million_usd=6.4,
            reasoning=False,
            multimodal=False,
            fine_tune_available=False,
            knowledge_cutoff=None,
            architecture="Hosted Qwen MoE flagship",
            deployment_options=_API,
            typical_use_cases=["Chinese/English flagship chat", "agents"],
            strengths=["high Arena-style quality", "strong coding"],
            limitations=["API-only", "limited Western enterprise footprint"],
            safety_notes="Alibaba Cloud content policies.",
            documentation_url="https://www.alibabacloud.com/help/en/model-studio/",
            benchmarks={"mmlu": 87.9, "arena_elo": 1332},
        ),
        _model(
            "qwen3-235b",
            "Qwen3-235B-A22B",
            "Alibaba",
            family="Qwen3",
            release_date="2025-04-29",
            modality="text",
            context_window_tokens=131072,
            max_output_tokens=32768,
            parameters="235B MoE (22B active)",
            license_name="Apache 2.0",
            open_weights=True,
            availability="weights and API",
            input_price_per_million_usd=0.2,
            output_price_per_million_usd=0.8,
            reasoning=True,
            multimodal=False,
            fine_tune_available=True,
            knowledge_cutoff=None,
            architecture="Qwen3 MoE with thinking/non-thinking modes",
            deployment_options=_API_WEIGHTS,
            typical_use_cases=["open reasoning", "agents", "multilingual"],
            strengths=["Apache license", "hybrid thinking", "strong multilingual"],
            limitations=["MoE serving complexity"],
            safety_notes="Open model; configure refusal behavior yourself.",
            documentation_url="https://qwenlm.github.io/blog/qwen3/",
            benchmarks={"gpqa": 71.1, "aime": 81.5, "mmlu": 87.8},
        ),
        _model(
            "command-r-plus",
            "Command R+",
            "Cohere",
            family="Command R",
            release_date="2024-04-04",
            modality="text",
            context_window_tokens=128000,
            max_output_tokens=4096,
            parameters="104B",
            license_name="CC-BY-NC / API commercial",
            open_weights=True,
            availability="weights and API",
            input_price_per_million_usd=2.5,
            output_price_per_million_usd=10.0,
            reasoning=False,
            multimodal=False,
            fine_tune_available=True,
            knowledge_cutoff=None,
            architecture="RAG-optimized Command model",
            deployment_options=_API_WEIGHTS,
            typical_use_cases=["enterprise RAG", "grounded generation", "tool use"],
            strengths=["citations", "RAG", "enterprise controls"],
            limitations=["weights are non-commercial"],
            safety_notes="Cohere safety and RAG grounding tools on API.",
            documentation_url="https://docs.cohere.com/docs/command-r-plus",
            benchmarks={"mmlu": 75.7, "nq": 50.3},
        ),
        _model(
            "command-a",
            "Command A",
            "Cohere",
            family="Command A",
            release_date="2025-03-13",
            modality="text",
            context_window_tokens=256000,
            max_output_tokens=8192,
            parameters="111B",
            license_name="CC-BY-NC / API commercial",
            open_weights=True,
            availability="weights and API",
            input_price_per_million_usd=2.5,
            output_price_per_million_usd=10.0,
            reasoning=False,
            multimodal=False,
            fine_tune_available=True,
            knowledge_cutoff=None,
            architecture="Efficient 111B enterprise model",
            deployment_options=_API_WEIGHTS,
            typical_use_cases=["enterprise agents", "RAG", "multilingual business"],
            strengths=["efficiency vs size", "enterprise features"],
            limitations=["non-commercial weights license"],
            safety_notes="Cohere platform safety features.",
            documentation_url="https://docs.cohere.com/docs/command-a",
            benchmarks={"mmlu": 85.5, "if_eval": 89.0},
        ),
        _model(
            "grok-3",
            "Grok 3",
            "xAI",
            family="Grok 3",
            release_date="2025-02-19",
            modality="text",
            context_window_tokens=131072,
            max_output_tokens=8192,
            parameters=None,
            license_name="Proprietary",
            open_weights=False,
            availability="API",
            input_price_per_million_usd=3.0,
            output_price_per_million_usd=15.0,
            reasoning=True,
            multimodal=False,
            fine_tune_available=False,
            knowledge_cutoff=None,
            architecture="xAI flagship with Think mode",
            deployment_options=_API,
            typical_use_cases=["search-augmented chat", "reasoning", "coding"],
            strengths=["Think mode", "real-time X integration in consumer apps"],
            limitations=["less enterprise documentation than peers"],
            safety_notes="xAI usage policies; consumer Grok and API differ.",
            documentation_url="https://docs.x.ai/docs/models",
            benchmarks={"gpqa": 80.2, "aime": 93.3},
        ),
        _model(
            "grok-4",
            "Grok 4",
            "xAI",
            family="Grok 4",
            release_date="2025-07-09",
            modality="multimodal",
            context_window_tokens=256000,
            max_output_tokens=16384,
            parameters=None,
            license_name="Proprietary",
            open_weights=False,
            availability="API",
            input_price_per_million_usd=3.0,
            output_price_per_million_usd=15.0,
            reasoning=True,
            multimodal=True,
            fine_tune_available=False,
            knowledge_cutoff=None,
            architecture="Next xAI flagship with native tool use",
            deployment_options=_API,
            typical_use_cases=["flagship assistant", "research", "coding agents"],
            strengths=["high reasoning scores", "multimodal"],
            limitations=["rapid SKU changes", "limited independent evals"],
            safety_notes="Verify current xAI policy for the specific SKU.",
            documentation_url="https://docs.x.ai/docs/models",
            benchmarks={"gpqa": 88.4, "swe_bench": 72.0},
        ),
        _model(
            "amazon-nova-pro",
            "Amazon Nova Pro",
            "Amazon",
            family="Nova",
            release_date="2024-12-03",
            modality="multimodal",
            context_window_tokens=300000,
            max_output_tokens=5000,
            parameters=None,
            license_name="Proprietary",
            open_weights=False,
            availability="API",
            input_price_per_million_usd=0.8,
            output_price_per_million_usd=3.2,
            reasoning=False,
            multimodal=True,
            fine_tune_available=True,
            knowledge_cutoff=None,
            architecture="Bedrock-hosted Nova multimodal",
            deployment_options=["Amazon Bedrock"],
            typical_use_cases=["AWS enterprise apps", "document/video understanding"],
            strengths=["AWS IAM/VPC", "multimodal", "cost"],
            limitations=["AWS-only", "smaller independent benchmark set"],
            safety_notes="Bedrock Guardrails can be attached.",
            documentation_url="https://docs.aws.amazon.com/nova/",
            benchmarks={"mmlu": 85.1, "mmmu": 64.0},
        ),
        _model(
            "amazon-nova-lite",
            "Amazon Nova Lite",
            "Amazon",
            family="Nova",
            release_date="2024-12-03",
            modality="multimodal",
            context_window_tokens=300000,
            max_output_tokens=5000,
            parameters=None,
            license_name="Proprietary",
            open_weights=False,
            availability="API",
            input_price_per_million_usd=0.06,
            output_price_per_million_usd=0.24,
            reasoning=False,
            multimodal=True,
            fine_tune_available=True,
            knowledge_cutoff=None,
            architecture="Low-cost Nova multimodal",
            deployment_options=["Amazon Bedrock"],
            typical_use_cases=["high-volume classification", "cheap vision"],
            strengths=["very low price", "Bedrock integration"],
            limitations=["weaker than Pro"],
            safety_notes="Use Bedrock Guardrails for production.",
            documentation_url="https://docs.aws.amazon.com/nova/",
            benchmarks={"mmlu": 80.5},
        ),
        _model(
            "amazon-nova-micro",
            "Amazon Nova Micro",
            "Amazon",
            family="Nova",
            release_date="2024-12-03",
            modality="text",
            context_window_tokens=128000,
            max_output_tokens=5000,
            parameters=None,
            license_name="Proprietary",
            open_weights=False,
            availability="API",
            input_price_per_million_usd=0.035,
            output_price_per_million_usd=0.14,
            reasoning=False,
            multimodal=False,
            fine_tune_available=True,
            knowledge_cutoff=None,
            architecture="Text-only Nova micro model",
            deployment_options=["Amazon Bedrock"],
            typical_use_cases=["routing", "classification", "cheap chat"],
            strengths=["lowest Nova price", "low latency"],
            limitations=["text only", "limited depth"],
            safety_notes="Bedrock Guardrails recommended.",
            documentation_url="https://docs.aws.amazon.com/nova/",
            benchmarks={"mmlu": 77.6},
        ),
        _model(
            "phi-4",
            "Phi-4",
            "Microsoft",
            family="Phi-4",
            release_date="2024-12-12",
            modality="text",
            context_window_tokens=16384,
            max_output_tokens=4096,
            parameters="14B",
            license_name="MIT",
            open_weights=True,
            availability="weights and API",
            input_price_per_million_usd=0.07,
            output_price_per_million_usd=0.14,
            reasoning=False,
            multimodal=False,
            fine_tune_available=True,
            knowledge_cutoff="2024-06",
            architecture="Small dense model trained with synthetic data",
            deployment_options=_API_WEIGHTS,
            typical_use_cases=["on-device", "edge", "cheap reasoning-lite"],
            strengths=["quality at 14B", "MIT license"],
            limitations=["short context vs frontier", "less world knowledge"],
            safety_notes="Open weights; Azure AI Foundry offers hosted filters.",
            documentation_url="https://azure.microsoft.com/en-us/products/phi-3",
            benchmarks={"mmlu": 84.8, "gpqa": 56.1},
        ),
        _model(
            "phi-4-reasoning",
            "Phi-4-reasoning",
            "Microsoft",
            family="Phi-4",
            release_date="2025-04-30",
            modality="text",
            context_window_tokens=32768,
            max_output_tokens=16384,
            parameters="14B",
            license_name="MIT",
            open_weights=True,
            availability="weights and API",
            input_price_per_million_usd=0.07,
            output_price_per_million_usd=0.14,
            reasoning=True,
            multimodal=False,
            fine_tune_available=True,
            knowledge_cutoff="2024-06",
            architecture="Phi-4 trained for long chain-of-thought",
            deployment_options=_API_WEIGHTS,
            typical_use_cases=["local STEM", "education", "cheap reasoning"],
            strengths=["open reasoning at small size"],
            limitations=["verbose", "limited tool ecosystem vs frontier APIs"],
            safety_notes="Traces may need redaction in user-facing apps.",
            documentation_url="https://huggingface.co/microsoft/Phi-4-reasoning",
            benchmarks={"aime": 75.3, "gpqa": 61.9},
        ),
        _model(
            "phi-3-5-moe",
            "Phi-3.5-MoE",
            "Microsoft",
            family="Phi-3.5",
            release_date="2024-08-20",
            modality="text",
            context_window_tokens=131072,
            max_output_tokens=4096,
            parameters="42B MoE (6.6B active)",
            license_name="MIT",
            open_weights=True,
            availability="weights and API",
            input_price_per_million_usd=0.13,
            output_price_per_million_usd=0.52,
            reasoning=False,
            multimodal=False,
            fine_tune_available=True,
            knowledge_cutoff="2024-04",
            architecture="Mixture-of-Experts Phi",
            deployment_options=_API_WEIGHTS,
            typical_use_cases=["efficient multilingual", "Azure on-prem"],
            strengths=["MoE efficiency", "long context"],
            limitations=["superseded in part by Phi-4"],
            safety_notes="MIT license; safety is deployer-owned.",
            documentation_url="https://huggingface.co/microsoft/Phi-3.5-MoE-instruct",
            benchmarks={"mmlu": 78.9},
        ),
        _model(
            "nemotron-70b",
            "Llama-3.1-Nemotron-70B Instruct",
            "NVIDIA",
            family="Nemotron",
            release_date="2024-10-15",
            modality="text",
            context_window_tokens=131072,
            max_output_tokens=4096,
            parameters="70B",
            license_name="NVIDIA Open Model License / Llama license",
            open_weights=True,
            availability="weights and API",
            input_price_per_million_usd=0.24,
            output_price_per_million_usd=0.24,
            reasoning=False,
            multimodal=False,
            fine_tune_available=True,
            knowledge_cutoff=None,
            architecture="Llama 3.1 70B aligned with NVIDIA RLHF",
            deployment_options=_API_WEIGHTS,
            typical_use_cases=["NIM microservices", "open chat", "reward-model related stacks"],
            strengths=["strong Arena score for 70B", "NVIDIA NIM"],
            limitations=["stacked licenses"],
            safety_notes="NVIDIA open model terms plus Llama AUP.",
            documentation_url="https://build.nvidia.com/nvidia/llama-3_1-nemotron-70b-instruct",
            benchmarks={"arena_elo": 1269, "mmlu": 83.3},
        ),
        _model(
            "embed-v3",
            "Cohere Embed v3",
            "Cohere",
            family="Embed",
            release_date="2023-11-02",
            modality="embedding",
            context_window_tokens=512,
            max_output_tokens=None,
            parameters=None,
            license_name="Proprietary API / limited weights",
            open_weights=False,
            availability="API",
            input_price_per_million_usd=0.1,
            output_price_per_million_usd=None,
            reasoning=False,
            multimodal=False,
            fine_tune_available=True,
            knowledge_cutoff=None,
            architecture="Text embedding encoder with compression",
            deployment_options=_API,
            typical_use_cases=["search", "clustering", "RAG"],
            strengths=["strong retrieval", "int8/binary compression"],
            limitations=["not a generative model"],
            safety_notes="Embeddings can still leak sensitive similarity structure.",
            documentation_url="https://docs.cohere.com/docs/cohere-embed",
            benchmarks={"mteb": 64.5},
        ),
        _model(
            "text-embedding-3-large",
            "text-embedding-3-large",
            "OpenAI",
            family="Embedding v3",
            release_date="2024-01-25",
            modality="embedding",
            context_window_tokens=8191,
            max_output_tokens=None,
            parameters=None,
            license_name="Proprietary",
            open_weights=False,
            availability="API",
            input_price_per_million_usd=0.13,
            output_price_per_million_usd=None,
            reasoning=False,
            multimodal=False,
            fine_tune_available=False,
            knowledge_cutoff=None,
            architecture="Matryoshka embedding model",
            deployment_options=_API,
            typical_use_cases=["RAG", "search", "clustering"],
            strengths=["quality", "shortening dimensions"],
            limitations=["API-only", "not generative"],
            safety_notes="Do not embed secrets you cannot store.",
            documentation_url="https://platform.openai.com/docs/guides/embeddings",
            benchmarks={"mteb": 64.6},
        ),
        _model(
            "sd-3-5-large",
            "Stable Diffusion 3.5 Large",
            "Stability AI",
            family="Stable Diffusion 3.5",
            release_date="2024-10-22",
            modality="image",
            context_window_tokens=77,
            max_output_tokens=None,
            parameters="8.1B",
            license_name="Stability AI Community License",
            open_weights=True,
            availability="weights and API",
            input_price_per_million_usd=None,
            output_price_per_million_usd=None,
            reasoning=False,
            multimodal=True,
            fine_tune_available=True,
            knowledge_cutoff=None,
            architecture="Multimodal diffusion transformer",
            deployment_options=_API_WEIGHTS,
            typical_use_cases=["image generation", "design", "concept art"],
            strengths=["open image generation", "prompt fidelity"],
            limitations=["not a language model", "license revenue cap"],
            safety_notes="Image safety filters vary by host; CSAM and public-figure policy needed.",
            documentation_url="https://stability.ai/news/introducing-stable-diffusion-3-5",
            benchmarks={"dpg_bench": 84.7},
        ),
        _model(
            "flux-1-dev",
            "FLUX.1 [dev]",
            "Black Forest Labs",
            family="FLUX.1",
            release_date="2024-08-01",
            modality="image",
            context_window_tokens=512,
            max_output_tokens=None,
            parameters="12B",
            license_name="FLUX.1 [dev] Non-Commercial License",
            open_weights=True,
            availability="weights and API",
            input_price_per_million_usd=None,
            output_price_per_million_usd=None,
            reasoning=False,
            multimodal=True,
            fine_tune_available=True,
            knowledge_cutoff=None,
            architecture="Rectified flow transformer",
            deployment_options=_API_WEIGHTS,
            typical_use_cases=["high-quality still images", "LoRA fine-tunes"],
            strengths=["photorealism", "text rendering vs older SD"],
            limitations=["dev license is non-commercial"],
            safety_notes="Operator must enforce prohibited content policies.",
            documentation_url="https://blackforestlabs.ai/",
            benchmarks={"elo": "high human preference"},
        ),
        _model(
            "midjourney-v7",
            "Midjourney v7",
            "Midjourney",
            family="Midjourney",
            release_date="2025-04-03",
            modality="image",
            context_window_tokens=None,
            max_output_tokens=None,
            parameters=None,
            license_name="Midjourney Terms of Service",
            open_weights=False,
            availability="hosted product",
            input_price_per_million_usd=None,
            output_price_per_million_usd=None,
            reasoning=False,
            multimodal=True,
            fine_tune_available=False,
            knowledge_cutoff=None,
            architecture="Proprietary image generation system",
            deployment_options=["Midjourney web/Discord"],
            typical_use_cases=["concept art", "marketing visuals", "exploration"],
            strengths=["aesthetic quality", "iterative UX"],
            limitations=["no API weights", "ToS and copyright constraints"],
            safety_notes="Platform moderation; commercial rights depend on subscription.",
            documentation_url="https://docs.midjourney.com/",
            benchmarks={},
        ),
        _model(
            "sora",
            "Sora",
            "OpenAI",
            family="Sora",
            release_date="2024-12-09",
            modality="video",
            context_window_tokens=None,
            max_output_tokens=None,
            parameters=None,
            license_name="Proprietary",
            open_weights=False,
            availability="hosted product",
            input_price_per_million_usd=None,
            output_price_per_million_usd=None,
            reasoning=False,
            multimodal=True,
            fine_tune_available=False,
            knowledge_cutoff=None,
            architecture="Diffusion transformer for video",
            deployment_options=["ChatGPT / Sora app"],
            typical_use_cases=["short video generation", "storyboarding"],
            strengths=["temporal coherence vs early video models"],
            limitations=["access controls", "limited duration", "no weights"],
            safety_notes="C2PA provenance, likeness and photorealism restrictions.",
            documentation_url="https://openai.com/sora",
            benchmarks={},
        ),
        _model(
            "veo-2",
            "Veo 2",
            "Google",
            family="Veo",
            release_date="2024-12-16",
            modality="video",
            context_window_tokens=None,
            max_output_tokens=None,
            parameters=None,
            license_name="Proprietary",
            open_weights=False,
            availability="API / Vertex",
            input_price_per_million_usd=None,
            output_price_per_million_usd=None,
            reasoning=False,
            multimodal=True,
            fine_tune_available=False,
            knowledge_cutoff=None,
            architecture="Google video generation model",
            deployment_options=["Vertex AI", "Gemini app"],
            typical_use_cases=["cinematic clips", "product videos"],
            strengths=["physics and detail", "Google Cloud path"],
            limitations=["cost per second", "policy limits"],
            safety_notes="SynthID watermarking and Google content policy.",
            documentation_url="https://cloud.google.com/vertex-ai/generative-ai/docs/video/overview",
            benchmarks={},
        ),
        _model(
            "runway-gen-3",
            "Runway Gen-3 Alpha",
            "Runway",
            family="Gen-3",
            release_date="2024-06-17",
            modality="video",
            context_window_tokens=None,
            max_output_tokens=None,
            parameters=None,
            license_name="Runway Terms",
            open_weights=False,
            availability="hosted product",
            input_price_per_million_usd=None,
            output_price_per_million_usd=None,
            reasoning=False,
            multimodal=True,
            fine_tune_available=False,
            knowledge_cutoff=None,
            architecture="Proprietary video diffusion/transformer stack",
            deployment_options=["Runway web"],
            typical_use_cases=["text/image-to-video", "creative production"],
            strengths=["creative controls", "production tooling"],
            limitations=["credits pricing", "closed model"],
            safety_notes="Runway content moderation and commercial terms.",
            documentation_url="https://runwayml.com/",
            benchmarks={},
        ),
        _model(
            "whisper-large-v3",
            "Whisper large-v3",
            "OpenAI",
            family="Whisper",
            release_date="2023-11-06",
            modality="audio",
            context_window_tokens=None,
            max_output_tokens=None,
            parameters="1550M",
            license_name="MIT",
            open_weights=True,
            availability="weights and API",
            input_price_per_million_usd=None,
            output_price_per_million_usd=None,
            reasoning=False,
            multimodal=False,
            fine_tune_available=True,
            knowledge_cutoff=None,
            architecture="Encoder-decoder ASR/translation",
            deployment_options=_API_WEIGHTS,
            typical_use_cases=["transcription", "translation", "subtitles"],
            strengths=["open ASR standard", "many languages"],
            limitations=["hallucinated transcripts", "weak diarization"],
            safety_notes="Audio can include PII; handle transcripts as sensitive.",
            documentation_url="https://github.com/openai/whisper",
            benchmarks={"fleurs": 8.1},
        ),
        _model(
            "jamba-1-5-large",
            "Jamba 1.5 Large",
            "AI21 Labs",
            family="Jamba 1.5",
            release_date="2024-08-22",
            modality="text",
            context_window_tokens=256000,
            max_output_tokens=4096,
            parameters="94B hybrid SSM-Transformer",
            license_name="Jamba Open Model License / API",
            open_weights=True,
            availability="weights and API",
            input_price_per_million_usd=2.0,
            output_price_per_million_usd=8.0,
            reasoning=False,
            multimodal=False,
            fine_tune_available=True,
            knowledge_cutoff=None,
            architecture="Hybrid Mamba-Transformer MoE",
            deployment_options=_API_WEIGHTS,
            typical_use_cases=["long-context enterprise", "RAG"],
            strengths=["long context efficiency", "open hybrid architecture"],
            limitations=["smaller ecosystem than Llama/Mistral"],
            safety_notes="AI21 Studio safety tools on API.",
            documentation_url="https://www.ai21.com/jamba",
            benchmarks={"mmlu": 81.2},
        ),
        _model(
            "yi-lightning",
            "Yi-Lightning",
            "01.AI",
            family="Yi",
            release_date="2024-10-16",
            modality="text",
            context_window_tokens=16384,
            max_output_tokens=4096,
            parameters=None,
            license_name="Proprietary API",
            open_weights=False,
            availability="API",
            input_price_per_million_usd=0.14,
            output_price_per_million_usd=0.14,
            reasoning=False,
            multimodal=False,
            fine_tune_available=False,
            knowledge_cutoff=None,
            architecture="MoE Yi API model",
            deployment_options=_API,
            typical_use_cases=["low-cost chat", "Chinese/English"],
            strengths=["Arena-competitive cost"],
            limitations=["API-only Lightning SKU", "limited Western support"],
            safety_notes="01.AI platform policies.",
            documentation_url="https://platform.lingyiwanwu.com/",
            benchmarks={"arena_elo": 1287},
        ),
        _model(
            "glm-4-plus",
            "GLM-4-Plus",
            "Zhipu AI",
            family="GLM-4",
            release_date="2024-08-21",
            modality="multimodal",
            context_window_tokens=128000,
            max_output_tokens=4096,
            parameters=None,
            license_name="Proprietary API / GLM open variants",
            open_weights=False,
            availability="API",
            input_price_per_million_usd=6.88,
            output_price_per_million_usd=6.88,
            reasoning=False,
            multimodal=True,
            fine_tune_available=True,
            knowledge_cutoff=None,
            architecture="GLM-4 hosted flagship",
            deployment_options=_API,
            typical_use_cases=["Chinese enterprise", "agents", "vision"],
            strengths=["strong Chinese tasks", "tool use"],
            limitations=["region and language of documentation"],
            safety_notes="Zhipu platform moderation.",
            documentation_url="https://open.bigmodel.cn/",
            benchmarks={"mmlu": 86.5, "alignbench": 8.0},
        ),
        _model(
            "kimi-k2",
            "Kimi K2",
            "Moonshot AI",
            family="Kimi",
            release_date="2025-07-11",
            modality="text",
            context_window_tokens=128000,
            max_output_tokens=16384,
            parameters="1T MoE (32B active)",
            license_name="Modified MIT",
            open_weights=True,
            availability="weights and API",
            input_price_per_million_usd=0.6,
            output_price_per_million_usd=2.5,
            reasoning=True,
            multimodal=False,
            fine_tune_available=True,
            knowledge_cutoff=None,
            architecture="Ultra-large MoE with agentic training",
            deployment_options=_API_WEIGHTS,
            typical_use_cases=["open agents", "coding", "long tasks"],
            strengths=["open trillion-scale MoE", "agentic coding"],
            limitations=["serving footprint", "license modifications"],
            safety_notes="Open model; agent tools need sandboxing.",
            documentation_url="https://moonshotai.github.io/Kimi-K2/",
            benchmarks={"swe_bench": 65.8, "livecodebench": 53.7},
        ),
        _model(
            "minimax-m1",
            "MiniMax-M1",
            "MiniMax",
            family="MiniMax-M1",
            release_date="2025-06-16",
            modality="text",
            context_window_tokens=1000000,
            max_output_tokens=32768,
            parameters="456B MoE",
            license_name="MiniMax Model License",
            open_weights=True,
            availability="weights and API",
            input_price_per_million_usd=0.4,
            output_price_per_million_usd=2.2,
            reasoning=True,
            multimodal=False,
            fine_tune_available=True,
            knowledge_cutoff=None,
            architecture="Lightning Attention MoE with RL reasoning",
            deployment_options=_API_WEIGHTS,
            typical_use_cases=["long-context reasoning", "open agents"],
            strengths=["1M context", "open reasoning"],
            limitations=["custom license", "infra cost"],
            safety_notes="Operator-owned safety for weights.",
            documentation_url="https://www.minimax.io/",
            benchmarks={"gpqa": 68.0, "swe_bench": 56.0},
        ),
        _model(
            "dbrx-instruct",
            "DBRX Instruct",
            "Databricks",
            family="DBRX",
            release_date="2024-03-27",
            modality="text",
            context_window_tokens=32768,
            max_output_tokens=4096,
            parameters="132B MoE (36B active)",
            license_name="Databricks Open Model License",
            open_weights=True,
            availability="weights and API",
            input_price_per_million_usd=0.75,
            output_price_per_million_usd=2.25,
            reasoning=False,
            multimodal=False,
            fine_tune_available=True,
            knowledge_cutoff="2023-12",
            architecture="Fine-grained MoE trained by Databricks/Mosaic",
            deployment_options=_API_WEIGHTS,
            typical_use_cases=["enterprise Mosaic/Databricks stacks", "open MoE"],
            strengths=["open MoE from Databricks", "coding"],
            limitations=["older vs 2025 flagships", "custom license"],
            safety_notes="Databricks open model terms.",
            documentation_url="https://www.databricks.com/blog/introducing-dbrx-new-state-art-open-llm",
            benchmarks={"mmlu": 73.7, "humaneval": 70.1},
        ),
        _model(
            "snowflake-arctic",
            "Snowflake Arctic",
            "Snowflake",
            family="Arctic",
            release_date="2024-04-24",
            modality="text",
            context_window_tokens=4096,
            max_output_tokens=4096,
            parameters="480B MoE (17B active)",
            license_name="Apache 2.0",
            open_weights=True,
            availability="weights and API",
            input_price_per_million_usd=0.8,
            output_price_per_million_usd=0.8,
            reasoning=False,
            multimodal=False,
            fine_tune_available=True,
            knowledge_cutoff=None,
            architecture="Dense-MoE hybrid trained for enterprise SQL/code",
            deployment_options=_API_WEIGHTS,
            typical_use_cases=["SQL generation", "enterprise Cortex", "open MoE"],
            strengths=["Apache license", "enterprise SQL focus"],
            limitations=["short context vs 2025 models"],
            safety_notes="Open weights; Snowflake Cortex adds governance when hosted.",
            documentation_url="https://www.snowflake.com/en/blog/arctic-open-efficient-foundation-models-enterprise/",
            benchmarks={"mmlu": 67.3, "humaneval": 64.3},
        ),
        _model(
            "falcon3-10b",
            "Falcon3-10B-Instruct",
            "TII",
            family="Falcon 3",
            release_date="2024-12-17",
            modality="text",
            context_window_tokens=32768,
            max_output_tokens=8192,
            parameters="10B",
            license_name="Falcon 3 License (TII)",
            open_weights=True,
            availability="weights",
            input_price_per_million_usd=None,
            output_price_per_million_usd=None,
            reasoning=False,
            multimodal=False,
            fine_tune_available=True,
            knowledge_cutoff=None,
            architecture="Dense decoder from Technology Innovation Institute",
            deployment_options=_WEIGHTS,
            typical_use_cases=["efficient open chat", "multilingual", "on-prem"],
            strengths=["small high-quality open model", "multilingual"],
            limitations=["smaller ecosystem than Llama"],
            safety_notes="TII license and acceptable use apply.",
            documentation_url="https://huggingface.co/tiiuae/Falcon3-10B-Instruct",
            benchmarks={"mmlu": 73.1},
        ),
        _model(
            "olmo-2-32b",
            "OLMo 2 32B Instruct",
            "Allen Institute for AI",
            family="OLMo 2",
            release_date="2025-01-07",
            modality="text",
            context_window_tokens=4096,
            max_output_tokens=2048,
            parameters="32B",
            license_name="Apache 2.0",
            open_weights=True,
            availability="weights",
            input_price_per_million_usd=None,
            output_price_per_million_usd=None,
            reasoning=False,
            multimodal=False,
            fine_tune_available=True,
            knowledge_cutoff=None,
            architecture="Fully open model with open data and training code",
            deployment_options=_WEIGHTS,
            typical_use_cases=["research", "fully open stacks", "science"],
            strengths=["open data/code/weights", "scientific transparency"],
            limitations=["not frontier quality", "shorter context"],
            safety_notes="Research-oriented open release; no hosted safety SLA.",
            documentation_url="https://allenai.org/olmo",
            benchmarks={"mmlu": 70.4},
        ),
        _model(
            "aya-expanse-32b",
            "Aya Expanse 32B",
            "Cohere For AI",
            family="Aya",
            release_date="2024-10-24",
            modality="text",
            context_window_tokens=131072,
            max_output_tokens=4096,
            parameters="32B",
            license_name="CC-BY-NC",
            open_weights=True,
            availability="weights and API",
            input_price_per_million_usd=0.5,
            output_price_per_million_usd=1.5,
            reasoning=False,
            multimodal=False,
            fine_tune_available=True,
            knowledge_cutoff=None,
            architecture="Massively multilingual open model",
            deployment_options=_API_WEIGHTS,
            typical_use_cases=["multilingual assistants", "localization", "research"],
            strengths=["23+ core languages", "open multilingual research"],
            limitations=["non-commercial weights license"],
            safety_notes="Cohere For AI research terms; NC license.",
            documentation_url="https://cohere.com/research/aya",
            benchmarks={"m_mmlu": 69.1},
        ),
        _model(
            "titan-embed-v2",
            "Amazon Titan Text Embeddings V2",
            "Amazon",
            family="Titan",
            release_date="2024-04-30",
            modality="embedding",
            context_window_tokens=8192,
            max_output_tokens=None,
            parameters=None,
            license_name="Proprietary",
            open_weights=False,
            availability="API",
            input_price_per_million_usd=0.02,
            output_price_per_million_usd=None,
            reasoning=False,
            multimodal=False,
            fine_tune_available=False,
            knowledge_cutoff=None,
            architecture="Flexible-dimension Bedrock embedding model",
            deployment_options=["Amazon Bedrock"],
            typical_use_cases=["AWS RAG", "search", "clustering"],
            strengths=["cheap embeddings", "IAM/VPC"],
            limitations=["AWS-only", "not generative"],
            safety_notes="Bedrock account controls; embeddings still store semantic PII.",
            documentation_url="https://docs.aws.amazon.com/bedrock/latest/userguide/titan-embedding-models.html",
            benchmarks={"mteb": 62.0},
        ),
        _model(
            "dall-e-3",
            "DALL·E 3",
            "OpenAI",
            family="DALL·E",
            release_date="2023-10-03",
            modality="image",
            context_window_tokens=4000,
            max_output_tokens=None,
            parameters=None,
            license_name="Proprietary",
            open_weights=False,
            availability="API",
            input_price_per_million_usd=None,
            output_price_per_million_usd=None,
            reasoning=False,
            multimodal=True,
            fine_tune_available=False,
            knowledge_cutoff=None,
            architecture="Text-to-image diffusion with LLM prompt rewriter",
            deployment_options=_API,
            typical_use_cases=["illustration", "concept images", "product mockups"],
            strengths=["prompt following", "safety system"],
            limitations=["per-image pricing", "stylistic constraints"],
            safety_notes="Prompt filters, C2PA in some products, no public-figure photorealism.",
            documentation_url="https://platform.openai.com/docs/guides/images",
            benchmarks={},
            extra={"pricing_notes": "Priced per image (standard ~$0.04–$0.12), not per token."},
        ),
    ]
